# Generated by Django 4.2.3 on 2025-09-23 17:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('lote', models.CharField(db_index=True, default='SIN-LOTE', max_length=50)),
                ('ubicacion', models.CharField(db_index=True, default='SIN-UBICACION', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['ubicacion', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(db_index=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'ordering': ['numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField(db_index=True)),
                ('numero_conteo', models.IntegerField(db_index=True)),
                ('cantidad_encontrada', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ubicacion_real', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evidencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventario.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField(db_index=True)),
                ('numero_conteo', models.IntegerField(db_index=True)),
                ('ubicacion_real', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['grupo', 'numero_conteo'], name='inventario__grupo_825547_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subzona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subzonas', to='inventario.zona')),
            ],
            options={
                'ordering': ['zona', 'nombre'],
                'indexes': [models.Index(fields=['zona', 'nombre'], name='inventario__zona_id_ee1a76_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subzona',
            constraint=models.UniqueConstraint(fields=('nombre', 'zona'), name='uq_subzona_nombre_zona'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('numero_lote', 'producto'), name='uq_lote_numero_producto'),
        ),
        migrations.AddIndex(
            model_name='conteo',
            index=models.Index(fields=['grupo', 'numero_conteo'], name='inventario__grupo_e127ac_idx'),
        ),
        migrations.AddIndex(
            model_name='conteo',
            index=models.Index(fields=['lote'], name='inventario__lote_id_b2def6_idx'),
        ),
    ]
