# Generated by Django 5.2.3 on 2025-07-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.etiqueta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('subzona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.subzona')),
            ],
        ),
    ]
