# Generated by Django 4.2.3 on 2025-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='subzona',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(default='SIN-CODIGO', max_length=50),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.CharField(default='SIN-PRODUCTO', max_length=255),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(default='SIN-UBICACION', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='lote',
            field=models.CharField(default='SIN-LOTE', max_length=50),
        ),
    ]
