# Generated by Django 4.2.3 on 2025-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_inventario_etiqueta_remove_inventario_subzona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
