# Generated by Django 5.2.3 on 2025-07-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote'),
        ),
    ]
