# Generated by Django 4.2.3 on 2025-07-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventario_producto_alter_inventario_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conteo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='cantidad_encontrada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='evidencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conteo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='inventario.lote'),
        ),
    ]
