services:
  - type: web
    name: conteo-inventario
    env: python
    buildCommand: |
      echo "=== INSTALANDO DEPENDENCIAS ==="
      pip install -r requirements.txt
      
      echo "=== EJECUTANDO COLLECTSTATIC ==="
      python manage.py collectstatic --noinput --verbosity=2

      echo "=== APLICANDO MIGRACIONES ==="
      python manage.py migrate
    startCommand: gunicorn inventario_project.wsgi:application