services:
  - type: web
    name: conteo-inventario
    env: python
    buildCommand: |
      echo "=== INSTALANDO DEPENDENCIAS ==="
      pip install -r requirements.txt

      echo "=== COLECTANDO ARCHIVOS ESTÁTICOS ==="
      python manage.py collectstatic --noinput --verbosity=2

      echo "=== MARCANDO MIGRACIONES DEL SISTEMA COMO FAKE ==="
      python manage.py migrate contenttypes 0001_initial --fake
      python manage.py migrate auth 0001_initial --fake
      python manage.py migrate admin 0001_initial --fake
      python manage.py migrate sessions 0001_initial --fake

      echo "=== MARCANDO MIGRACIONES DE LA APP INVENTARIO COMO FAKE ==="
      python manage.py migrate inventario 0001_initial --fake
      python manage.py migrate inventario 0002_inventario --fake
      python manage.py migrate inventario 0003_alter_conteo_lote --fake

      echo "=== MARCANDO TODO COMO APLICADO ==="
      python manage.py migrate --fake

    startCommand: gunicorn inventario_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventario_project.settings
      - key: DATABASE_URL
        value: postgresql://inventario_db_1sxp_user:Iwa7y3rROLZyuUKuK9g8fHgWEwLSCiog@dpg-d1r8odruibrs73f9n2lg-a.oregon-postgres.render.com/inventario_db_1sxp