services:
  - type: web
    name: conteo-inventario
    env: python
    buildCommand: |
      echo "=== INSTALANDO DEPENDENCIAS ==="
      pip install -r requirements.txt

      echo "=== STATIC ==="
      python manage.py collectstatic --noinput --verbosity=2

      echo "=== MIGRACIONES SISTEMA COMO FAKE INITIAL ==="
      python manage.py migrate contenttypes 0001_initial --fake
      python manage.py migrate auth 0001_initial --fake
      python manage.py migrate admin 0001_initial --fake
      python manage.py migrate sessions 0001_initial --fake

      echo "=== MARCAR MIGRACIONES POSTERIORES DEL SISTEMA ==="
      python manage.py migrate --fake

      echo "=== MARCAR 0001 de INVENTARIO COMO FAKE ==="
      python manage.py migrate inventario 0001_initial --fake

      echo "=== MARCAR TODAS LAS DEMÁS MIGRACIONES DE INVENTARIO COMO FAKE ==="
      python manage.py migrate inventario --fake

    startCommand: gunicorn inventario_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventario_project.settings
      - key: DATABASE_URL
        value: postgresql://inventario_db_1sxp_user:Iwa7y3rROLZyuUKuK9g8fHgWEwLSCiog@dpg-d1r8odruibrs73f9n2lg-a.oregon-postgres.render.com/inventario_db_1sxp