services:
  - type: web
    name: conteo-inventario
    env: python
    buildCommand: |
      echo "=== INSTALANDO DEPENDENCIAS ==="
      pip install -r requirements.txt

      echo "=== EJECUTANDO COLLECTSTATIC ==="
      python manage.py collectstatic --noinput --verbosity=2

      echo "=== APLICANDO MIGRACIONES ==="
      python manage.py migrate --fake-initial

    startCommand: gunicorn inventario_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventario_project.settings
      - key: DATABASE_URL
        value: postgresql://inventario_db_1sxp_user:Iwa7y3rROLZyuUKuK9g8fHgWEwLSCiog@dpg-d1r8odruibrs73f9n2lg-a.oregon-postgres.render.com/inventario_db_1sxp